let bannedWords = [
        "abortion",
        "accessibility",
        "Accessible",
        "activism",
        "activist",
        "advocacy",
        "advocate",
        "affirmative action",
        "affirming care",
        "affordable home",
        "affordable housing",
        "agricultural water",
        "agrivoltaics",
        "air pollution",
        "all-inclusive",
        "allyship",
        "alternative energy",
        "anti-racism",
        "antiracist",
        "asexual",
        "assigned at birth",
        "assigned female at birth",
        "afab",
        "assigned male at birth",
        "amab",
        "at risk",
        "autism",
        "aviation fuel",
        "barrier",
        "belong",
        "bias",
        "biased",
        "Biased toward",
        "biases",
        "Biases towards",
        "bioenergy",
        "biofuel",
        "biogas",
        "biologically female",
        "biologically male",
        "biomethane",
        "bipoc",
        "bisexual",
        "Black",
        "black and latinx",
        "breastfeed&people",
        "breastfeed&person",
        "Cancer Moonshot",
        "carbon emissions mitigation",
        "carbon footprint",
        "carbon markets",
        "carbon pricing",
        "carbon sequestration",
        "CEC",
        "changing climate",
        "chestfeed&people",
        "chestfeed&person",
        "clean energy",
        "clean fuel",
        "clean power",
        "clean water",
        "climate",
        "climate accountability",
        "climate change",
        "climate consulting",
        "climate crisis",
        "climate model",
        "climate resilience",
        "climate risk",
        "climate science",
        "climate smart agriculture",
        "climate smart forestry",
        "climate variability",
        "climate-change",
        "climatesmart",
        "commercial sex worker",
        "community",
        "community diversity",
        "community equity",
        "confirmation bias",
        "contaminants of environmental concern",
        "continuum",
        "Covid-19",
        "critical race theory",
        "cultural competence",
        "cultural differences",
        "cultural heritage",
        "Cultural relevance",
        "cultural sensitivity",
        "culturally appropriate",
        "culturally responsive",
        "decarbonization",
        "definition",
        "DEI",
        "DEIA",
        "DEIAB",
        "DEIJ",
        "diesel",
        "dietary guidelines",
        "ultraprocessed foods",
        "dirty energy",
        "disabilities",
        "disability",
        "disabled",
        "disadvantaged",
        "discriminated",
        "discrimination",
        "discriminatory",
        "discussion of federal policies",
        "disparity",
        "diverse",
        "diverse backgrounds",
        "diverse communities",
        "diverse community",
        "diverse group",
        "diverse groups",
        "diversified",
        "diversify",
        "diversifying",
        "diversity",
        "diversity and inclusion",
        "diversity in the workplace",
        "diversity, equity, and inclusion",
        "diversity efforts",
        "equity efforts",
        "EEJ",
        "EJ",
        "elderly",
        "electric vehicle",
        "emissions",
        "energy conversion",
        "energy transition",
        "enhance the diversity",
        "enhancing diversity",
        "entitlement",
        "environmental justice",
        "environmental quality",
        "equal opportunity",
        "equality",
        "equitable",
        "equitableness",
        "equity",
        "ethanol",
        "ethnicity",
        "evidence-based",
        "excluded",
        "exclusion",
        "expression",
        "female",
        "females",
        "feminist",
        "feminism",
        "fetus",
        "field drainage",
        "fluoride",
        "fostering inclusivity",
        "fuel cell",
        "gay",
        "GBV",
        "gender",
        "gender based",
        "gender based violence",
        "gender diversity",
        "gender dysphoria",
        "gender expression",
        "gender identity",
        "gender ideology",
        "gender nonconformity",
        "gender transition",
        "gender-affirming care",
        "gendered",
        "genders",
        "geothermal",
        "GHG emission",
        "GHG modeling",
        "GHG monitoring",
        "global warming",
        "green",
        "green infrastructure",
        "greenhouse gas emission",
        "groundwater pollution",
        "Gulf of Mexico",
        "H5N1",
        "bird flu",
        "hate",
        "hate speech",
        "health disparity",
        "health equity",
        "hispanic",
        "hispanic minority",
        "historically",
        "housing affordability",
        "housing efficiency",
        "hydrogen vehicle",
        "identity",
        "ideology",
        "immigration",
        "implicit bias",
        "inclusion",
        "inclusive",
        "inclusive leadership",
        "inclusiveness",
        "inclusivity",
        "Increase diversity",
        "increase the diversity",
        "indigenous",
        "indigenous community",
        "indigenous communities",
        "indigenous people",
        "inequalities",
        "inequality",
        "inequitable",
        "inequities",
        "injustice",
        "institutional",
        "integration",
        "intersectional",
        "intersectionality",
        "intersex",
        "issues concerning pending legislation",
        "justice",
        "key groups",
        "key people",
        "key populations",
        "Latinx",
        "lesbian",
        "lgbt",
        "LGBTQ",
        "low-emission vehicle",
        "low-income housing",
        "male dominated",
        "marginalize",
        "marginalized",
        "marijuana",
        "measles",
        "membrane filtration",
        "men who have sex with men",
        "mental health",
        "methane emissions",
        "microplastic",
        "migrant",
        "minorities",
        "minority",
        "minority serving institution",
        "most risk",
        "MSI",
        "msm",
        "multicultural",
        "Mx",
        "Native American",
        "NCI budget",
        "net-zero",
        "non-binary",
        "nonbinary",
        "noncitizen",
        "non-conforming",
        "nonpoint source pollution",
        "nuclear energy",
        "nuclear power",
        "obesity",
        "opioid",
        "oppression",
        "oppressive",
        "orientation",
        "pansexual",
        "PCB",
        "peanut allergies",
        "people&uterus",
        "people of color",
        "people-centered care",
        "person-centered",
        "person-centered care",
        "PFAS",
        "PFOA",
        "photovoltaic",
        "polarization",
        "political",
        "pollution",
        "pollution abatement",
        "pollution remediation",
        "prefabricated housing",
        "pregnant people",
        "pregnant person",
        "prejudice",
        "privilege",
        "promote",
        "promote diversity",
        "promoting diversity",
        "pronoun",
        "prostitute",
        "pyrolysis",
        "QT",
        "queer",
        "race",
        "race and ethnicity",
        "racial",
        "racial diversity",
        "racial identity",
        "racial inequality",
        "racial justice",
        "racially",
        "racism",
        "runoff",
        "rural water",
        "safe drinking water",
        "science-based",
        "sediment remediation",
        "segregation",
        "self-assessed",
        "sense of belonging",
        "sex",
        "sexual",
        "sexual preference",
        "sexuality",
        "social justice",
        "social vulnerability",
        "socio cultural",
        "socio economic",
        "sociocultural",
        "socioeconomic status",
        "soil pollution",
        "solar energy",
        "solar power",
        "special populations",
        "stem cell research",
        "fetal tissue research",
        "stereotype",
        "subsidized housing",
        "sustainability",
        "sustainable",
        "sustainable construction",
        "systemic",
        "tax breaks",
        "tax credits",
        "tax subsidies",
        "they/them",
        "tile drainage",
        "trans",
        "transexual",
        "transexualism",
        "transgender",
        "transgender military personnel",
        "transgender people",
        "transitional housing",
        "trauma",
        "traumatic",
        "tribal",
        "two-spirit",
        "unconscious bias",
        "under appreciated",
        "under represented",
        "under served",
        "underprivileged",
        "underrepresentation",
        "underrepresented",
        "underserved",
        "understudied",
        "undervalued",
        "vaccines",
        "victim",
        "victims",
        "vulnerable",
        "vulnerable populations",
        "water collection",
        "water conservation",
        "water distribution",
        "water efficiency",
        "water management",
        "water pollution",
        "water quality",
        "water storage",
        "water treatment",
        "white privilege",
        "wind power",
        "woman",
        "women",
        "women in leadership"
    ];

cleanBannedWords()

function cleanBannedWords() {
    for (let i = 0; i < bannedWords.length; i++) {
        bannedWords[i] = bannedWords[i].trim().toLowerCase();
    }
}

function clickAction() {
    const userProp = document.getElementById('user-input').innerHTML.toString();
    document.getElementById('output').innerHTML = wordSearch(userProp);
}

function wordSearch(toSearch) {
    let foundWords = [];
    let revisedProp = toSearch;
    for (let i = bannedWords.length-1; i >= 0; i--) {
        const word = bannedWords[i];
        const pattern = new RegExp(word, 'gi');
        if (pattern.test(revisedProp)) {
            const found = revisedProp.match(pattern);
            const item = { term: word, count: found.length }
            foundWords.push(item);
            revisedProp = revisedProp.replace(pattern, '<flag>' + word + '</flag>');
        }
    }
    formatFoundWords(foundWords);
    return revisedProp;
}

function formatFoundWords(foundWords) {
    document.getElementById("output-list").innerHTML = '';
    if (foundWords.length > 0) {
        if (foundWords.length > 1){
            foundWords.sort(compare);
        }
        for (let i = 0; i < foundWords.length; i++) {
            const listItem = document.createElement('li');
            const format = foundWords[i].term + " (" + String(foundWords[i].count) + ")"
            listItem.innerHTML = format;
            document.getElementById('output-list').appendChild(listItem);
        }
    } else {
        const listItem = document.createElement('li');
        listItem.innerHTML = 'No words found';
        document.getElementById('output-list').appendChild(listItem);
    }
}





let compare = (a, b) => {
    if (a.count > b.count){
        return -1;
    } else if (a.count == b.count){
        return a.term.localeCompare(b.term);
    } else {
        return 1;
    }
}
